### ISSUE TITLE
SmartComponent.smart_destroy() doesn't remove instance from parent component.

### ISSUE THREAD

**Issue by jberta93** [tipodisimmia/smartComponentJS#2]
SmartComponent.smart_destroy() doesn't remove instance from parent component.

The method destroy only component but it doesn't remove it from parent component.

Adding this code to method can fix this bug:

```javascript
if(!!this.parentComponent && !!this.parentComponent.components){
                delete this.parentComponent.components[this.componentReferenceName];
}
```

**Comment by tipodisimmia** [comment]
Bug resolved
